[package]
name = "ia-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
color-eyre = "0.6.3"
csv = "1.3.0"
serde = { version = "1.0.214", features = ["derive"] }
